#!/usr/bin/env bash
# This script is used to transfer a file from the client to the server

file_path=$1
server_IP=$2
user_name=$3
ssh_key=$4

if [ $# -lt  3 ];
then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
        scp -i $ssh_key -o StrictHostKeyChecking=no $file_path $user_name@$server_IP:~
fi
