#!/usr/bin/env bash
# This bash file installs nginx then configures its index page to display Hello World

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
sudo chmod 777 /var/www/html/index.html
sudo echo "Hello World!" > /var/www/html/index.html
sudo chmod 644 /var/www/html/index.html
sudo service nginx restart
