#!/usr/bin/env bash
# This bash file installs nginx then configures its index page to display Hello World

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
