#!/usr/bin/env bash
# This bash file installs nginx then configures its index page to display Hello World
# It also configures redirection to permanent links

link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
new_configuration="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/bravinatonya-alx.tech
sudo rm -rf /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/bravinatonya-alx.tech /etc/nginx/sites-enabled/bravinatonya-alx.tech
sudo sed -i "s|server_name\ _;|$new_configuration|" /etc/nginx/sites-available/bravinatonya-alx.tech
sudo service nginx restart
