#!/usr/bin/env bash
# This bash file installs nginx then configures its index page to display Hello World
# It also configures redirection to permanent links

link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
new_configuration="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
sudo chmod 777 /var/www/html/index.html
sudo echo "Hello World!" > /var/www/html/index.html
sudo chmod 644 /var/www/html/index.html
sudo sed -i "s|server_name\ _;|$new_configuration|" /etc/nginx/sites-available/default
sudo service nginx restart
