#!/usr/bin/env bash
# Script that configures HAproxy

sudo apt-get update

sudo apt-get install -y haproxy


sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend myfrontend
	bind *:80
	default_backend myservers

backend myservers
	balance roundrobin
	server 126259-web-01 52.91.149.35 check
	server 126259-web-02 34.232.67.76 check
EOT

sudo /etc/init.d/haproxy start

sudo update-rc.d haproxy defaults

sudo /etc/init.d/haproxy reload
