#!/usr/bin/env bash
# Script that configures HAproxy

sudo apt install haproxy
echo 'frontend myfrontend\n\tbind *:80\ndefault_backend myservers\n\n
backend myservers\n\tbalance roundrobin\n\t\tserver server1 52.91.149.35:80 check\n\t\tserver server2 34.232.67.76:80 check\n' >> /etc/haproxy/haproxy.cfg

