#!/usr/bin/env bash
#This is a bash script that displays listening ports:
#That only shows listening sockets
#That shows the PID and name of the program to which each socket belongs
sudo netstat -l --program
