#!/usr/bin/env bash
# -Creates the file '/var/run/myscript.pid' containing its PID
# -Displays 'To infinity and beyond' indefinitely
# -Displays 'I hate the kill command' when receiving a SIGTERM signal
# -Displays 'Y U no love me?!' when receiving a SIGINT signal
# - Deletes the file '/var/run/myscript.pid' and terminates itself when receiving a SIGQUIT or SIGTERM signal

process_PID=$BASHPID
echo $process_PID > /var/run/myscript.pid

while true
do
echo "To infinity and beyond"
done

function SIGTERM_signal()
{
	echo "Ihate the kill command"
	rm -rf /var/run/myscript.pid
	kill -9 $process_PID
}

function SIGINT_signal()
{
	echo "Y U no love me?!"
}
function SIGQUIT_signal()
{
	rm -rf /var/run/myscript.pid
	kill -9 $process_PID
}

trap SIGQUIT_signal SIGQUIT
trap SIGINT_signal SIGINT
trap SIGTERM_signal SIGTERM
