#!/usr/bin/env bash
#prints To infinity and beyond indefinitely and listens for the for the SIGTERM signal

trap 'echo "I am invincible!!!" ' TERM

while :
do
echo "To infinity and beyond"
sleep 2
done
