#!/usr/bin/env bash
# This bash file prints 1-100 with fizzBuzz

counter=1
while [ $counter -le "100" ]
do
	if ((counter % 3 == 0 && counter % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((counter % 3 == 0))
	then
		echo "Fizz"
	elif ((counter % 5 == 0))
	then
		echo "Buzz"
	else
		echo $counter
	fi
	counter=$(( counter +1 ))
done
