#!/usr/bin/env bash
# This bash script prints Best School 10 times but changes the output in 9th iteration

counter=0

while [ $counter -lt 10 ]
do
if [ $counter -eq 8 ]
then
echo "Best School"
echo "Hi"
else
echo "Best School"
fi
counter=$(( counter+1 ))
done
