#!/usr//bin/env bash
# Stops apache then trys to run nginx as nginx

pkill apache2

if grep -q "80" /etc/nginx/sites-available/default ; then
	sed -i "s/80/8080" /etc/nginx/sites-available/default
fi

chown nginx:nginx /etc/nginx/nginx.conf

chmod 0644 /etc/nginx/nginx.conf

su nginx -c "service nginx start"
