#!/usr//bin/env bash
# Stops apache then trys to run nginx as nginx

pkill apache2

# change IPV4 listening port if it is 80 to 8080
if grep -q "listen 80" /etc/nginx/sites-available/default ; then
    sed -i "s/listen 80/listen 8080/" /etc/nginx/sites-available/default
fi

# change IPV6 listening port if it is 80 to 8080
if grep -q "listen \[::\]:80" /etc/nginx/sites-available/default ; then
    sed -i "s/listen \[::\]:80/listen \[::\]:8080/" /etc/nginx/sites-available/default
fi

chown nginx:nginx /etc/nginx/nginx.conf

chmod 0644 /etc/nginx/nginx.conf

su nginx -c "service nginx start"
